### PR TITLE
WIP: Fix invalidations

### PR DESCRIPTION
**Pull request by frapac**

### CODE REVIEW

**Comment by frapac** [comment]
For the parser, note that: 
>while Julia itself has made a lot of progress, there’s still more that can be done. Most of the remaining vulnerabilities seem to be in the area of string-processing, an area that hasn’t received much attention yet. Even simple packages like FilePathsBase still trigger hundreds of invalidations, and we could use one or more heroes to step forward and get this straightened out

In https://discourse.julialang.org/t/finding-and-fixing-invalidations-now-everyone-can-help-reduce-time-to-first-plot/45598

**Comment by michel2323** [comment]
Fix for KA 0.6.1 is underway https://github.com/JuliaGPU/KernelAbstractions.jl/pull/245

**Comment by michel2323** [comment]
I pinned `develop` to KA 0.6.0. Maybe we can rebase this for now.

**Review by michel2323 — APPROVED** [review]

**Comment by michel2323** [comment]
This still needs a rebase right?

**Pull request closed without merging**
