### PR TITLE
Add a cache to avoid allocating on the GPU

### PR DESCRIPTION
**Pull request by frapac**
This PR adds a new object `NetworkState` to cache the intermediate results in `ReducedSpaceNLPEvaluator`. The goal is to avoid as much as possible allocating new array on the GPU. 

The most important points are: 
- the logic of `PolarModel` has been updated. Now we pass a triplet `x, u, p` to a `NetworkState` at the *beginning*, and then we work exclusively with this cache. All values are modified inplace (so we should be careful with the possible side effects). 
- no kernel are implemented, yet. But I think now we have the correct structure to implement them (we need to, to avoid computing cos and sin on the CPU whenever we are working with `CuArrays`).
- this PR updated the structure of the `src/models/polar`, to avoid large `.jl` file. 
- to me, the new logic of the second layer is twofold: first we propagate **forward** the value of a triplet *(x, u, p)*, in the sense `(x, u, p) -> NetworkState -> Pg, Qg -> evaluate objective & constraints`. Then, we compute the adjoint in a **backward** fashion. Hence the splitting between the files `forward.jl` and `adjoints.jl`. 

Also, `cache` is not a well appropriate name. All suggestion are welcome to update it :-) 

**WARNING:** Before merging this PR, I should ensure that everything is working fine on the different test cases. At the moment I have tested only with `case9`, `case30` and `case300`.

### CODE REVIEW

**Comment by frapac** [comment]
To complete the description, here is a benchmark between `dev/rgm` and this PR: 

- `dev/rgm` 
```
Device: CPU()
Constructor       0.000410 seconds (956 allocations: 121.203 KiB)
Update            0.000429 seconds (601 allocations: 185.688 KiB)
Objective         0.000057 seconds (41 allocations: 2.344 KiB)
Gradient          0.000164 seconds (256 allocations: 54.914 KiB)
Constrt           0.000038 seconds (74 allocations: 3.688 KiB)
Jacobian          0.000598 seconds (1.05 k allocations: 432.969 KiB)
Device: CUDADevice()
Constructor       0.013516 seconds (8.44 k allocations: 396.766 KiB)
Update            0.011273 seconds (10.30 k allocations: 415.266 KiB)
Objective         0.001536 seconds (2.08 k allocations: 68.297 KiB)
Gradient          0.022352 seconds (12.52 k allocations: 537.141 KiB)
Constrt           0.002724 seconds (2.75 k allocations: 101.812 KiB)
Jacobian          0.145546 seconds (52.59 k allocations: 2.066 MiB)

## case300.m
Device: CPU()
Constructor       0.007231 seconds (28.27 k allocations: 4.652 MiB)
Update            0.011990 seconds (797 allocations: 4.794 MiB)
Objective         0.000058 seconds (95 allocations: 16.312 KiB)
Gradient          0.001927 seconds (394 allocations: 866.766 KiB)
Constrt           0.000098 seconds (404 allocations: 31.125 KiB)
Jacobian        Device: CUDADevice()
Constructor       1.415997 seconds (196.77 k allocations: 19.642 MiB)
Update            0.155788 seconds (25.66 k allocations: 1.800 MiB)
Objective         0.004763 seconds (5.32 k allocations: 210.234 KiB)
Gradient         15.295399 seconds (3.19 M allocations: 197.796 MiB, 0.33% gc time)
Constrt           0.037844 seconds (7.00 k allocations: 523.594 KiB)
```

- this PR: 
```
## case9.m
Device: CPU()
Constructor       0.000415 seconds (927 allocations: 121.531 KiB)
Update            0.000434 seconds (438 CPU allocations: 165.766 KiB)
Objective         0.000025 seconds (8 CPU allocations: 240 bytes)
Gradient          0.000130 seconds (95 CPU allocations: 40.117 KiB)
Constrt           0.000082 seconds (77 CPU allocations: 3.750 KiB)
Device: CUDADevice()
Constructor       0.019168 seconds (5.94 k allocations: 439.328 KiB)
Update            0.008129 seconds (5.26 k CPU allocations: 254.969 KiB)
Objective         0.000211 seconds (32 CPU allocations: 1.781 KiB)
Gradient          0.006432 seconds (1.44 k CPU allocations: 92.219 KiB)
Constrt           0.002241 seconds (2.07 k CPU allocations: 91.078 KiB) (18 GPU allocations: 648 bytes, 0.99% gc time)

## case300.m
Device: CPU()
Constructor       0.006929 seconds (28.03 k allocations: 4.647 MiB)
Update            0.011251 seconds (661 CPU allocations: 4.044 MiB)
Objective         0.000034 seconds (8 CPU allocations: 240 bytes)
Gradient          0.001809 seconds (97 CPU allocations: 689.594 KiB)
Constrt           0.000140 seconds (407 CPU allocations: 31.188 KiB)
Device: CUDADevice()
Constructor       2.394358 seconds (320.02 k allocations: 32.008 MiB)
Update            0.112239 seconds (17.35 k CPU allocations: 1.239 MiB)
Objective         0.002886 seconds (560 CPU allocations: 35.812 KiB)
Gradient          2.553268 seconds (387.20 k CPU allocations: 30.669 MiB)
Constrt           0.037475 seconds (7.00 k CPU allocations: 523.656 KiB) (18 GPU allocations: 21.609 KiB, 0.06% gc time)
```

**Comment by frapac** [comment]
More information on the gradients & derivative checks: 
- `test_rgm` converges in the expected number of iterations (78), to the correct solution
- current code passes Ipopt's derivative check on all the instances I checked (`case118`, `case300`, `case1353pegase`)

**Comment by frapac** [comment]
The last benchmark gives, on `case300.m`: 

```
## case300.m
[ Info: CPU
Constructor       0.013581 seconds (27.57 k CPU allocations: 4.640 MiB)
Update            0.008374 seconds (696 CPU allocations: 4.047 MiB)
Objective         0.000070 seconds (12 CPU allocations: 864 bytes)
Gradient          0.001426 seconds (100 CPU allocations: 689.547 KiB)
Constrt           0.000073 seconds (13 CPU allocations: 432 bytes)
[ Info: GPU
Constructor       0.291129 seconds (132.16 k CPU allocations: 9.767 MiB) (61 GPU allocations: 866.215 KiB, 0.21% gc time of which 79.42% spent allocating)
Update            0.059990 seconds (17.26 k CPU allocations: 678.312 KiB) (3 GPU allocations: 4.141 KiB, 0.04% gc time of which 59.07% spent allocating)
Objective         0.000482 seconds (318 CPU allocations: 12.297 KiB) (2 GPU allocations: 560 bytes, 7.47% gc time of which 83.94% spent allocating)
Gradient          0.064219 seconds (29.13 k CPU allocations: 1.176 MiB) (1 GPU allocation: 1.070 KiB, 0.02% gc time of which 50.28% spent allocating)
Constrt           0.016834 seconds (6.17 k CPU allocations: 256.703 KiB)

```

We have more allocations on the GPU now, as sometimes they are necessary to get better performance.

**Review by michel2323 — APPROVED** [review]
Looks good to me!

**Pull request merged**
